const footballersData = [
    {name: "Lionel Messi", team: "Barcelona", position: "Attaquant", goals: 703},
    {name: "Erling Haaland", team: "Manchester City", position: "Attaquant", goals: 190},
    {name: "Cristiano Ronaldo", team: "Al Nasr", position: "Attaquant", goals: 898},
    {name: "Kylian Mbappé", team: "Paris Saint-Germain", position: "Attaquant", goals: 280},
    {name: "Neymar Jr", team: "Paris Saint-Germain", position: "Attaquant", goals: 250},
    {name: "Robert Lewandowski", team: "Bayern Munich", position: "Attaquant", goals: 486},
    {name: "Mohamed Salah", team: "Liverpool", position: "Attaquant", goals: 280},
    {name: "Harry Kane", team: "Tottenham", position: "Attaquant", goals: 213},
    {name: "Sergio Aguero", team: "Barcelona", position: "Attaquant", goals: 446},
    {name: "Raheem Sterling", team: "Manchester City", position: "Attaquant", goals: 205},
    {name: "Sadio Mane", team: "Liverpool", position: "Attaquant", goals: 164},
    {name: "Bernardo Silva", team: "Manchester City", position: "Milieu", goals: 57},
    {name: "Kevin De Bruyne", team: "Manchester City", position: "Milieu", goals: 47},
    {name: "Paul Pogba", team: "Manchester United", position: "Milieu", goals: 36},
    {name: "Frenkie de Jong", team: "Barcelona", position: "Milieu", goals: 9},
    {name: "Tanguy Ndombele", team: "Tottenham", position: "Milieu", goals: 11},
    {name: "Bruno Fernandes", team: "Manchester United", position: "Milieu", goals: 34},
    {name: "Kai Havertz", team: "Chelsea", position: "Milieu", goals: 17},
    {name: "Houssem Aouar", team: "Lyon", position: "Milieu", goals: 24},
    {name: "Luka Modric", team: "Real Madrid", position: "Milieu", goals: 45},
    {name: "Virgil van Dijk", team: "Liverpool", position: "Défenseur", goals: 14},
    {name: "Kalidou Koulibaly", team: "Napoli", position: "Défenseur", goals: 8},
    {name: "Aymeric Laporte", team: "Manchester City", position: "Défenseur", goals: 12},
    {name: "Sergio Ramos", team: "Real Madrid", position: "Défenseur", goals: 101},
    {name: "Jan Vertonghen", team: "Tottenham", position: "Défenseur", goals: 15},
    {name: "Raphael Varane", team: "Real Madrid", position: "Défenseur", goals: 18},
    {name: "Trent Alexander-Arnold", team: "Liverpool", position: "Défenseur", goals: 8},
    {name: "Andrew Robertson", team: "Liverpool", position: "Défenseur", goals: 11},
    {name: "Jan Oblak", team: "Atletico Madrid", position: "Gardien", goals: 0},
    {name: "Alisson Becker", team: "Liverpool", position: "Gardien", goals: 0},
    {name: "Manuel Neuer", team: "Bayern Munich", position: "Gardien", goals: 0},
    {name: "Marc-Andre ter Stegen", team: "Barcelona", position: "Gardien", goals: 0},
    {name: "Keylor Navas", team: "Paris Saint-Germain", position: "Gardien", goals: 0},
    {name: "Jan Bednarek", team: "Southampton", position: "Défenseur", goals: 3},
    {name: "Jorginho", team: "Chelsea", position: "Milieu", goals: 10},
    {name: "Rodrigo", team: "Leeds United", position: "Milieu", goals: 4},
    {name: "Reece James", team: "Chelsea", position: "Défenseur", goals: 1},
    {name: "Riyad Mahrez", team: "Manchester City", position: "Milieu", goals: 31},
    {name: "Phil Foden", team: "Manchester City", position: "Milieu", goals: 20},
    {name: "Joao Cancelo", team: "Manchester City", position: "Défenseur", goals: 4},
    {name: "Ruben Dias", team: "Manchester City", position: "Défenseur", goals: 2},
    {name: "Ilkay Gundogan", team: "Manchester City", position: "Milieu", goals: 16},
    {name: "Raúl Jiménez", team: "Wolves", position: "Attaquant", goals: 62},
    {name: "John Stones", team: "Manchester City", position: "Défenseur", goals: 5},
    {name: "Angel Di Maria", team: "Paris Saint-Germain", position: "Milieu", goals: 77},
    {name: "Kostas Manolas", team: "Napoli", position: "Défenseur", goals: 8},
    {name: "Piotr Zielinski", team: "Napoli", position: "Milieu", goals: 19},
    {name: "Dries Mertens", team: "Napoli", position: "Attaquant", goals: 121},
    {name: "Jose Callejon", team: "Fiorentina", position: "Attaquant", goals: 52},
    {name: "Hirving Lozano", team: "Napoli", position: "Attaquant", goals: 34},
    {name: "Arkadiusz Milik", team: "Marseille", position: "Attaquant", goals: 78},
    {name: "Fabian Ruiz", team: "Napoli", position: "Milieu", goals: 19},
    {name: "Allan", team: "Napoli", position: "Milieu", goals: 7},
    {name: "Stanislav Lobotka", team: "Napoli", position: "Milieu", goals: 5},
    {name: "Eljif Elmas", team: "Napoli", position: "Milieu", goals: 7},
    {name: "Lorenzo Insigne", team: "Napoli", position: "Attaquant", goals: 115},
    {name: "David Ospina", team: "Napoli", position: "Gardien", goals: 0},
    {name: "Kevin Malcuit", team: "Napoli", position: "Défenseur", goals: 2},
    {name: "Elseid Hysaj", team: "Napoli", position: "Défenseur", goals: 5},
    {name: "Nikola Maksimovic", team: "Napoli", position: "Défenseur", goals: 4},
    {name: "Faouzi Ghoulam", team: "Napoli", position: "Défenseur", goals: 3},
];

export default footballersData;
